// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/auth.dart';
import 'api/client.dart';
import 'api/media.dart';
import 'api/oidc.dart';
import 'api/recovery.dart';
import 'api/rooms.dart';
import 'api/search.dart';
import 'api/threads.dart';
import 'api/timeline.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MatrixClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_OidcLoginPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RoomTimelinePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  MatrixClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    dynamic raw,
  );

  @protected
  OidcLogin
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    dynamic raw,
  );

  @protected
  RoomTimeline
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    dynamic raw,
  );

  @protected
  MatrixClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    dynamic raw,
  );

  @protected
  OidcLogin
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    dynamic raw,
  );

  @protected
  RoomTimeline
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    dynamic raw,
  );

  @protected
  MatrixClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    dynamic raw,
  );

  @protected
  OidcLogin
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    dynamic raw,
  );

  @protected
  RoomTimeline
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<String>> dco_decode_StreamSink_list_String_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<RoomSummary>> dco_decode_StreamSink_list_room_summary_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RecentThreadsSnapshot>
  dco_decode_StreamSink_recent_threads_snapshot_Sse(dynamic raw);

  @protected
  RustStreamSink<RecoveryStatus> dco_decode_StreamSink_recovery_status_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SessionEvent> dco_decode_StreamSink_session_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SyncStatus> dco_decode_StreamSink_sync_status_Sse(dynamic raw);

  @protected
  RustStreamSink<TimelineSnapshot> dco_decode_StreamSink_timeline_snapshot_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthError dco_decode_auth_error(dynamic raw);

  @protected
  AuthErrorKind dco_decode_auth_error_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MatrixClient
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ImageContent dco_decode_box_autoadd_image_content(dynamic raw);

  @protected
  LatestMessage dco_decode_box_autoadd_latest_message(dynamic raw);

  @protected
  MessageKind dco_decode_box_autoadd_message_kind(dynamic raw);

  @protected
  NewRoom dco_decode_box_autoadd_new_room(dynamic raw);

  @protected
  ReplyPreview dco_decode_box_autoadd_reply_preview(dynamic raw);

  @protected
  RoomEvent dco_decode_box_autoadd_room_event(dynamic raw);

  @protected
  ThreadInfo dco_decode_box_autoadd_thread_info(dynamic raw);

  @protected
  TimelineMessage dco_decode_box_autoadd_timeline_message(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateRoomError dco_decode_create_room_error(dynamic raw);

  @protected
  CreateRoomErrorKind dco_decode_create_room_error_kind(dynamic raw);

  @protected
  CreatedRoom dco_decode_created_room(dynamic raw);

  @protected
  FailedInvite dco_decode_failed_invite(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageContent dco_decode_image_content(dynamic raw);

  @protected
  InviteError dco_decode_invite_error(dynamic raw);

  @protected
  InviteErrorKind dco_decode_invite_error_kind(dynamic raw);

  @protected
  JoinRoomError dco_decode_join_room_error(dynamic raw);

  @protected
  JoinRoomErrorKind dco_decode_join_room_error_kind(dynamic raw);

  @protected
  LatestMessage dco_decode_latest_message(dynamic raw);

  @protected
  LatestMessageKind dco_decode_latest_message_kind(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FailedInvite> dco_decode_list_failed_invite(dynamic raw);

  @protected
  List<MessageHit> dco_decode_list_message_hit(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<RecentThread> dco_decode_list_recent_thread(dynamic raw);

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw);

  @protected
  List<TimelineEntry> dco_decode_list_timeline_entry(dynamic raw);

  @protected
  MediaError dco_decode_media_error(dynamic raw);

  @protected
  MediaErrorKind dco_decode_media_error_kind(dynamic raw);

  @protected
  MessageHit dco_decode_message_hit(dynamic raw);

  @protected
  MessageKind dco_decode_message_kind(dynamic raw);

  @protected
  MessageSearchPage dco_decode_message_search_page(dynamic raw);

  @protected
  NewRoom dco_decode_new_room(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MatrixClient?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ImageContent? dco_decode_opt_box_autoadd_image_content(dynamic raw);

  @protected
  LatestMessage? dco_decode_opt_box_autoadd_latest_message(dynamic raw);

  @protected
  MessageKind? dco_decode_opt_box_autoadd_message_kind(dynamic raw);

  @protected
  ReplyPreview? dco_decode_opt_box_autoadd_reply_preview(dynamic raw);

  @protected
  RoomEvent? dco_decode_opt_box_autoadd_room_event(dynamic raw);

  @protected
  ThreadInfo? dco_decode_opt_box_autoadd_thread_info(dynamic raw);

  @protected
  TimelineMessage? dco_decode_opt_box_autoadd_timeline_message(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  RecentThread dco_decode_recent_thread(dynamic raw);

  @protected
  RecentThreadsSnapshot dco_decode_recent_threads_snapshot(dynamic raw);

  @protected
  RecentThreadsStatus dco_decode_recent_threads_status(dynamic raw);

  @protected
  RecoveryError dco_decode_recovery_error(dynamic raw);

  @protected
  RecoveryErrorKind dco_decode_recovery_error_kind(dynamic raw);

  @protected
  RecoveryStatus dco_decode_recovery_status(dynamic raw);

  @protected
  ReplyPreview dco_decode_reply_preview(dynamic raw);

  @protected
  ReplyState dco_decode_reply_state(dynamic raw);

  @protected
  RoomActionError dco_decode_room_action_error(dynamic raw);

  @protected
  RoomActionErrorKind dco_decode_room_action_error_kind(dynamic raw);

  @protected
  RoomEvent dco_decode_room_event(dynamic raw);

  @protected
  RoomEventKind dco_decode_room_event_kind(dynamic raw);

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw);

  @protected
  SearchError dco_decode_search_error(dynamic raw);

  @protected
  SearchErrorKind dco_decode_search_error_kind(dynamic raw);

  @protected
  SendState dco_decode_send_state(dynamic raw);

  @protected
  SessionEvent dco_decode_session_event(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  ThreadInfo dco_decode_thread_info(dynamic raw);

  @protected
  TimelineEntry dco_decode_timeline_entry(dynamic raw);

  @protected
  TimelineError dco_decode_timeline_error(dynamic raw);

  @protected
  TimelineErrorKind dco_decode_timeline_error_kind(dynamic raw);

  @protected
  TimelineMessage dco_decode_timeline_message(dynamic raw);

  @protected
  TimelineSnapshot dco_decode_timeline_snapshot(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserCheck dco_decode_user_check(dynamic raw);

  @protected
  UserCheckStatus dco_decode_user_check_status(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  MatrixClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    SseDeserializer deserializer,
  );

  @protected
  OidcLogin
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    SseDeserializer deserializer,
  );

  @protected
  RoomTimeline
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    SseDeserializer deserializer,
  );

  @protected
  MatrixClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    SseDeserializer deserializer,
  );

  @protected
  OidcLogin
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    SseDeserializer deserializer,
  );

  @protected
  RoomTimeline
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    SseDeserializer deserializer,
  );

  @protected
  MatrixClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    SseDeserializer deserializer,
  );

  @protected
  OidcLogin
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    SseDeserializer deserializer,
  );

  @protected
  RoomTimeline
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<String>> sse_decode_StreamSink_list_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<RoomSummary>> sse_decode_StreamSink_list_room_summary_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RecentThreadsSnapshot>
  sse_decode_StreamSink_recent_threads_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RecoveryStatus> sse_decode_StreamSink_recovery_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SessionEvent> sse_decode_StreamSink_session_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatus> sse_decode_StreamSink_sync_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TimelineSnapshot> sse_decode_StreamSink_timeline_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthError sse_decode_auth_error(SseDeserializer deserializer);

  @protected
  AuthErrorKind sse_decode_auth_error_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MatrixClient
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageContent sse_decode_box_autoadd_image_content(
    SseDeserializer deserializer,
  );

  @protected
  LatestMessage sse_decode_box_autoadd_latest_message(
    SseDeserializer deserializer,
  );

  @protected
  MessageKind sse_decode_box_autoadd_message_kind(SseDeserializer deserializer);

  @protected
  NewRoom sse_decode_box_autoadd_new_room(SseDeserializer deserializer);

  @protected
  ReplyPreview sse_decode_box_autoadd_reply_preview(
    SseDeserializer deserializer,
  );

  @protected
  RoomEvent sse_decode_box_autoadd_room_event(SseDeserializer deserializer);

  @protected
  ThreadInfo sse_decode_box_autoadd_thread_info(SseDeserializer deserializer);

  @protected
  TimelineMessage sse_decode_box_autoadd_timeline_message(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateRoomError sse_decode_create_room_error(SseDeserializer deserializer);

  @protected
  CreateRoomErrorKind sse_decode_create_room_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  CreatedRoom sse_decode_created_room(SseDeserializer deserializer);

  @protected
  FailedInvite sse_decode_failed_invite(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageContent sse_decode_image_content(SseDeserializer deserializer);

  @protected
  InviteError sse_decode_invite_error(SseDeserializer deserializer);

  @protected
  InviteErrorKind sse_decode_invite_error_kind(SseDeserializer deserializer);

  @protected
  JoinRoomError sse_decode_join_room_error(SseDeserializer deserializer);

  @protected
  JoinRoomErrorKind sse_decode_join_room_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  LatestMessage sse_decode_latest_message(SseDeserializer deserializer);

  @protected
  LatestMessageKind sse_decode_latest_message_kind(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FailedInvite> sse_decode_list_failed_invite(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageHit> sse_decode_list_message_hit(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<RecentThread> sse_decode_list_recent_thread(
    SseDeserializer deserializer,
  );

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer);

  @protected
  List<TimelineEntry> sse_decode_list_timeline_entry(
    SseDeserializer deserializer,
  );

  @protected
  MediaError sse_decode_media_error(SseDeserializer deserializer);

  @protected
  MediaErrorKind sse_decode_media_error_kind(SseDeserializer deserializer);

  @protected
  MessageHit sse_decode_message_hit(SseDeserializer deserializer);

  @protected
  MessageKind sse_decode_message_kind(SseDeserializer deserializer);

  @protected
  MessageSearchPage sse_decode_message_search_page(
    SseDeserializer deserializer,
  );

  @protected
  NewRoom sse_decode_new_room(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MatrixClient?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageContent? sse_decode_opt_box_autoadd_image_content(
    SseDeserializer deserializer,
  );

  @protected
  LatestMessage? sse_decode_opt_box_autoadd_latest_message(
    SseDeserializer deserializer,
  );

  @protected
  MessageKind? sse_decode_opt_box_autoadd_message_kind(
    SseDeserializer deserializer,
  );

  @protected
  ReplyPreview? sse_decode_opt_box_autoadd_reply_preview(
    SseDeserializer deserializer,
  );

  @protected
  RoomEvent? sse_decode_opt_box_autoadd_room_event(
    SseDeserializer deserializer,
  );

  @protected
  ThreadInfo? sse_decode_opt_box_autoadd_thread_info(
    SseDeserializer deserializer,
  );

  @protected
  TimelineMessage? sse_decode_opt_box_autoadd_timeline_message(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  RecentThread sse_decode_recent_thread(SseDeserializer deserializer);

  @protected
  RecentThreadsSnapshot sse_decode_recent_threads_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  RecentThreadsStatus sse_decode_recent_threads_status(
    SseDeserializer deserializer,
  );

  @protected
  RecoveryError sse_decode_recovery_error(SseDeserializer deserializer);

  @protected
  RecoveryErrorKind sse_decode_recovery_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  RecoveryStatus sse_decode_recovery_status(SseDeserializer deserializer);

  @protected
  ReplyPreview sse_decode_reply_preview(SseDeserializer deserializer);

  @protected
  ReplyState sse_decode_reply_state(SseDeserializer deserializer);

  @protected
  RoomActionError sse_decode_room_action_error(SseDeserializer deserializer);

  @protected
  RoomActionErrorKind sse_decode_room_action_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  RoomEvent sse_decode_room_event(SseDeserializer deserializer);

  @protected
  RoomEventKind sse_decode_room_event_kind(SseDeserializer deserializer);

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer);

  @protected
  SearchError sse_decode_search_error(SseDeserializer deserializer);

  @protected
  SearchErrorKind sse_decode_search_error_kind(SseDeserializer deserializer);

  @protected
  SendState sse_decode_send_state(SseDeserializer deserializer);

  @protected
  SessionEvent sse_decode_session_event(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  ThreadInfo sse_decode_thread_info(SseDeserializer deserializer);

  @protected
  TimelineEntry sse_decode_timeline_entry(SseDeserializer deserializer);

  @protected
  TimelineError sse_decode_timeline_error(SseDeserializer deserializer);

  @protected
  TimelineErrorKind sse_decode_timeline_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  TimelineMessage sse_decode_timeline_message(SseDeserializer deserializer);

  @protected
  TimelineSnapshot sse_decode_timeline_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserCheck sse_decode_user_check(SseDeserializer deserializer);

  @protected
  UserCheckStatus sse_decode_user_check_status(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    MatrixClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    OidcLogin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    RoomTimeline self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    MatrixClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    OidcLogin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    RoomTimeline self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    MatrixClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    OidcLogin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    RoomTimeline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_String_Sse(
    RustStreamSink<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_room_summary_Sse(
    RustStreamSink<List<RoomSummary>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_recent_threads_snapshot_Sse(
    RustStreamSink<RecentThreadsSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_recovery_status_Sse(
    RustStreamSink<RecoveryStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_session_event_Sse(
    RustStreamSink<SessionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_Sse(
    RustStreamSink<SyncStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_timeline_snapshot_Sse(
    RustStreamSink<TimelineSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_error(AuthError self, SseSerializer serializer);

  @protected
  void sse_encode_auth_error_kind(AuthErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    MatrixClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_content(
    ImageContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_latest_message(
    LatestMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_kind(
    MessageKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_room(NewRoom self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_reply_preview(
    ReplyPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_room_event(
    RoomEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_info(
    ThreadInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timeline_message(
    TimelineMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_room_error(
    CreateRoomError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_room_error_kind(
    CreateRoomErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_created_room(CreatedRoom self, SseSerializer serializer);

  @protected
  void sse_encode_failed_invite(FailedInvite self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_content(ImageContent self, SseSerializer serializer);

  @protected
  void sse_encode_invite_error(InviteError self, SseSerializer serializer);

  @protected
  void sse_encode_invite_error_kind(
    InviteErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_join_room_error(JoinRoomError self, SseSerializer serializer);

  @protected
  void sse_encode_join_room_error_kind(
    JoinRoomErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_latest_message(LatestMessage self, SseSerializer serializer);

  @protected
  void sse_encode_latest_message_kind(
    LatestMessageKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_failed_invite(
    List<FailedInvite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_hit(
    List<MessageHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_recent_thread(
    List<RecentThread> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timeline_entry(
    List<TimelineEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_error(MediaError self, SseSerializer serializer);

  @protected
  void sse_encode_media_error_kind(
    MediaErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_hit(MessageHit self, SseSerializer serializer);

  @protected
  void sse_encode_message_kind(MessageKind self, SseSerializer serializer);

  @protected
  void sse_encode_message_search_page(
    MessageSearchPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_room(NewRoom self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    MatrixClient? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_image_content(
    ImageContent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_latest_message(
    LatestMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_kind(
    MessageKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reply_preview(
    ReplyPreview? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_room_event(
    RoomEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_info(
    ThreadInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_timeline_message(
    TimelineMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_recent_thread(RecentThread self, SseSerializer serializer);

  @protected
  void sse_encode_recent_threads_snapshot(
    RecentThreadsSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recent_threads_status(
    RecentThreadsStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_error(RecoveryError self, SseSerializer serializer);

  @protected
  void sse_encode_recovery_error_kind(
    RecoveryErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_status(
    RecoveryStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reply_preview(ReplyPreview self, SseSerializer serializer);

  @protected
  void sse_encode_reply_state(ReplyState self, SseSerializer serializer);

  @protected
  void sse_encode_room_action_error(
    RoomActionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_action_error_kind(
    RoomActionErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_room_event(RoomEvent self, SseSerializer serializer);

  @protected
  void sse_encode_room_event_kind(RoomEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer);

  @protected
  void sse_encode_search_error(SearchError self, SseSerializer serializer);

  @protected
  void sse_encode_search_error_kind(
    SearchErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_state(SendState self, SseSerializer serializer);

  @protected
  void sse_encode_session_event(SessionEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_thread_info(ThreadInfo self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_entry(TimelineEntry self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_error(TimelineError self, SseSerializer serializer);

  @protected
  void sse_encode_timeline_error_kind(
    TimelineErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_message(
    TimelineMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_snapshot(
    TimelineSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_check(UserCheck self, SseSerializer serializer);

  @protected
  void sse_encode_user_check_status(
    UserCheckStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMatrixClient(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerOidcLogin(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRoomTimeline(
    int ptr,
  );
}
