// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `finish_new_login`, `login_new_device`, `new`, `remove_failed_store`, `storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

class AuthError implements FrbException {
  final AuthErrorKind kind;
  final String message;

  const AuthError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum AuthErrorKind {
  invalidHomeserver,
  homeserverUnreachable,
  invalidCredentials,
  userDeactivated,
  rateLimited,
  storage,
  oidcNotSupported,
  authorizationDenied,
  timedOut,
  cancelled,
  unknown,
}
