// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `login_new_device`, `new`, `new`, `remove_failed_store`, `run_blocking`, `storage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  String get deviceId;

  static Future<MatrixClient> login({
    required String homeserver,
    required String username,
    required String password,
    required String dataDir,
  }) => RustLib.instance.api.crateApiAuthMatrixClientLogin(
    homeserver: homeserver,
    username: username,
    password: password,
    dataDir: dataDir,
  );

  Future<void> logout();

  static Future<MatrixClient?> restoreSession({required String dataDir}) =>
      RustLib.instance.api.crateApiAuthMatrixClientRestoreSession(
        dataDir: dataDir,
      );

  bool get sessionSaved;

  String get userId;
}

class AuthError implements FrbException {
  final AuthErrorKind kind;
  final String message;

  const AuthError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum AuthErrorKind {
  invalidHomeserver,
  homeserverUnreachable,
  invalidCredentials,
  userDeactivated,
  rateLimited,
  storage,
  unknown,
}
