// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'auth.dart';
import 'media.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'recovery.dart';
import 'rooms.dart';
import 'search.dart';
import 'threads.dart';
import 'timeline.dart';

// These functions are ignored because they are not marked as `pub`: `find_room`, `forget`, `new`, `new`, `run_blocking`, `save_on_refresh`, `save_tokens`, `stored`, `watch_action`, `watch_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Vault`, `WatchAction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MatrixClient>>
abstract class MatrixClient implements RustOpaqueInterface {
  Future<void> acceptInvite({required String roomId});

  Future<bool> canInvite({required String roomId});

  Future<UserCheck> checkUser({required String userId});

  Future<CreatedRoom> createRoom({required NewRoom room});

  Future<void> declineInvite({required String roomId});

  String get deviceId;

  Future<void> inviteUser({required String roomId, required String userId});

  Future<String> joinRoom({required String target});

  Future<void> leaveRoom({required String roomId});

  Future<Uint8List> loadMedia({required String media, required bool thumbnail});

  static Future<MatrixClient> login({
    required String homeserver,
    required String username,
    required String password,
    required String dataDir,
    required bool keepSignedIn,
  }) => RustLib.instance.api.crateApiClientMatrixClientLogin(
    homeserver: homeserver,
    username: username,
    password: password,
    dataDir: dataDir,
    keepSignedIn: keepSignedIn,
  );

  Future<void> logout();

  Future<RoomTimeline> openTimeline({required String roomId});

  Future<void> recover({required String recoveryKey});

  static Future<MatrixClient?> restoreSession({required String dataDir}) =>
      RustLib.instance.api.crateApiClientMatrixClientRestoreSession(
        dataDir: dataDir,
      );

  Future<void> retryRecentThreads();

  Future<String?> roomLink({required String roomId});

  Future<MessageSearchPage> searchMessages({
    required String term,
    String? nextBatch,
  });

  Stream<SessionEvent> sessionEvents();

  bool get sessionSaved;

  String get userId;

  Stream<RecentThreadsSnapshot> watchRecentThreads();

  Stream<RecoveryStatus> watchRecovery();

  Stream<List<RoomSummary>> watchRooms();

  Stream<SyncStatus> watchSyncStatus();
}

enum SessionEvent {
  revoked,
}
