// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `fmt`, `from`

class MediaError implements FrbException {
  final MediaErrorKind kind;
  final String message;

  const MediaError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum MediaErrorKind {
  invalidReference,
  network,
  unknown,
}
