// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'rooms.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

class RoomNotification {
  final String roomId;
  final String roomName;
  final bool isDirect;
  final bool isInvite;
  final String senderName;
  final LatestMessageKind kind;
  final String? body;
  final PlatformInt64 timestampMs;

  const RoomNotification({
    required this.roomId,
    required this.roomName,
    required this.isDirect,
    required this.isInvite,
    required this.senderName,
    required this.kind,
    this.body,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      roomName.hashCode ^
      isDirect.hashCode ^
      isInvite.hashCode ^
      senderName.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomNotification &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          roomName == other.roomName &&
          isDirect == other.isDirect &&
          isInvite == other.isInvite &&
          senderName == other.senderName &&
          kind == other.kind &&
          body == other.body &&
          timestampMs == other.timestampMs;
}
