// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'auth.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `prepare`, `registration_data`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PendingLogin`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OidcLogin>>
abstract class OidcLogin implements RustOpaqueInterface {
  String get authorizationUrl;

  Future<void> cancel();

  Future<MatrixClient> complete();

  static Future<OidcLogin> start({
    required String homeserver,
    required String dataDir,
  }) => RustLib.instance.api.crateApiOidcOidcLoginStart(
    homeserver: homeserver,
    dataDir: dataDir,
  );
}
