// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `recover`, `watch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`

class RecoveryError implements FrbException {
  final RecoveryErrorKind kind;
  final String message;

  const RecoveryError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveryError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum RecoveryErrorKind {
  invalidKey,
  network,
  unknown,
}

enum RecoveryStatus {
  unknown,
  enabled,
  disabled,

  /// A conta tem backup, mas este dispositivo ainda não tem a chave para abri-lo.
  incomplete,
}
