// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

class LatestMessage {
  final String senderName;
  final bool isOwn;
  final LatestMessageKind kind;
  final String? body;
  final PlatformInt64 timestampMs;

  const LatestMessage({
    required this.senderName,
    required this.isOwn,
    required this.kind,
    this.body,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      senderName.hashCode ^
      isOwn.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LatestMessage &&
          runtimeType == other.runtimeType &&
          senderName == other.senderName &&
          isOwn == other.isOwn &&
          kind == other.kind &&
          body == other.body &&
          timestampMs == other.timestampMs;
}

enum LatestMessageKind {
  text,
  image,
  file,
  encrypted,
  other,
}

class RoomSummary {
  final String id;
  final String name;
  final bool isDirect;
  final bool isInvite;
  final int unreadMessages;
  final int unreadMentions;
  final int unreadThreadReplies;
  final int memberCount;
  final List<String> heroes;
  final LatestMessage? latest;

  const RoomSummary({
    required this.id,
    required this.name,
    required this.isDirect,
    required this.isInvite,
    required this.unreadMessages,
    required this.unreadMentions,
    required this.unreadThreadReplies,
    required this.memberCount,
    required this.heroes,
    this.latest,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDirect.hashCode ^
      isInvite.hashCode ^
      unreadMessages.hashCode ^
      unreadMentions.hashCode ^
      unreadThreadReplies.hashCode ^
      memberCount.hashCode ^
      heroes.hashCode ^
      latest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDirect == other.isDirect &&
          isInvite == other.isInvite &&
          unreadMessages == other.unreadMessages &&
          unreadMentions == other.unreadMentions &&
          unreadThreadReplies == other.unreadThreadReplies &&
          memberCount == other.memberCount &&
          heroes == other.heroes &&
          latest == other.latest;
}

enum SyncStatus {
  connecting,
  running,
  offline,
  unsupported,
  error,
}
