// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_room_within`, `invited_room`, `join_room_within`, `parse_join_target`, `with_server_of_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

class CreateRoomError implements FrbException {
  final CreateRoomErrorKind kind;
  final String message;

  const CreateRoomError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateRoomError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum CreateRoomErrorKind {
  network,
  unknown,
}

class CreatedRoom {
  final String roomId;
  final List<String> failedInvites;

  const CreatedRoom({
    required this.roomId,
    required this.failedInvites,
  });

  @override
  int get hashCode => roomId.hashCode ^ failedInvites.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreatedRoom &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          failedInvites == other.failedInvites;
}

class InviteError implements FrbException {
  final InviteErrorKind kind;
  final String message;

  const InviteError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum InviteErrorKind {
  roomNotFound,
  network,
  unknown,
}

class JoinRoomError implements FrbException {
  final JoinRoomErrorKind kind;
  final String message;

  const JoinRoomError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinRoomError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum JoinRoomErrorKind {
  invalidLink,
  notFound,
  forbidden,
  network,
  unknown,
}

class LatestMessage {
  final String senderName;
  final bool isOwn;
  final LatestMessageKind kind;
  final String? body;
  final PlatformInt64 timestampMs;

  const LatestMessage({
    required this.senderName,
    required this.isOwn,
    required this.kind,
    this.body,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      senderName.hashCode ^
      isOwn.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LatestMessage &&
          runtimeType == other.runtimeType &&
          senderName == other.senderName &&
          isOwn == other.isOwn &&
          kind == other.kind &&
          body == other.body &&
          timestampMs == other.timestampMs;
}

enum LatestMessageKind {
  text,
  image,
  file,
  encrypted,
  other,
}

class NewRoom {
  final String name;
  final String? topic;
  final bool isPublic;
  final List<String> invites;

  const NewRoom({
    required this.name,
    this.topic,
    required this.isPublic,
    required this.invites,
  });

  @override
  int get hashCode =>
      name.hashCode ^ topic.hashCode ^ isPublic.hashCode ^ invites.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewRoom &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          topic == other.topic &&
          isPublic == other.isPublic &&
          invites == other.invites;
}

class RoomSummary {
  final String id;
  final String name;
  final bool isDirect;
  final bool isInvite;
  final bool isPublic;
  final int unreadMessages;
  final int unreadMentions;
  final int unreadThreadReplies;
  final int memberCount;
  final List<String> heroes;
  final LatestMessage? latest;

  const RoomSummary({
    required this.id,
    required this.name,
    required this.isDirect,
    required this.isInvite,
    required this.isPublic,
    required this.unreadMessages,
    required this.unreadMentions,
    required this.unreadThreadReplies,
    required this.memberCount,
    required this.heroes,
    this.latest,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isDirect.hashCode ^
      isInvite.hashCode ^
      isPublic.hashCode ^
      unreadMessages.hashCode ^
      unreadMentions.hashCode ^
      unreadThreadReplies.hashCode ^
      memberCount.hashCode ^
      heroes.hashCode ^
      latest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDirect == other.isDirect &&
          isInvite == other.isInvite &&
          isPublic == other.isPublic &&
          unreadMessages == other.unreadMessages &&
          unreadMentions == other.unreadMentions &&
          unreadThreadReplies == other.unreadThreadReplies &&
          memberCount == other.memberCount &&
          heroes == other.heroes &&
          latest == other.latest;
}

enum SyncStatus {
  connecting,
  running,
  offline,
  unsupported,
  error,
}

class UserCheck {
  final UserCheckStatus status;
  final String? displayName;

  const UserCheck({
    required this.status,
    this.displayName,
  });

  @override
  int get hashCode => status.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserCheck &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          displayName == other.displayName;
}

enum UserCheckStatus {
  found,
  notFound,
  unknown,
}
