// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hit`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

class MessageHit {
  final String roomId;
  final String roomName;
  final bool isDirect;
  final String eventId;
  final String senderName;
  final bool isOwn;
  final String body;
  final PlatformInt64 timestampMs;

  const MessageHit({
    required this.roomId,
    required this.roomName,
    required this.isDirect,
    required this.eventId,
    required this.senderName,
    required this.isOwn,
    required this.body,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      roomName.hashCode ^
      isDirect.hashCode ^
      eventId.hashCode ^
      senderName.hashCode ^
      isOwn.hashCode ^
      body.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageHit &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          roomName == other.roomName &&
          isDirect == other.isDirect &&
          eventId == other.eventId &&
          senderName == other.senderName &&
          isOwn == other.isOwn &&
          body == other.body &&
          timestampMs == other.timestampMs;
}

class MessageSearchPage {
  final List<MessageHit> hits;
  final String? nextBatch;

  const MessageSearchPage({
    required this.hits,
    this.nextBatch,
  });

  @override
  int get hashCode => hits.hashCode ^ nextBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageSearchPage &&
          runtimeType == other.runtimeType &&
          hits == other.hits &&
          nextBatch == other.nextBatch;
}

class SearchError implements FrbException {
  final SearchErrorKind kind;
  final String message;

  const SearchError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum SearchErrorKind {
  network,
  unknown,
}
