// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'rooms.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

class RecentThread {
  final String roomId;
  final String rootEventId;
  final LatestMessage root;
  final LatestMessage? latestReply;
  final int replyCount;
  final PlatformInt64 activityMs;

  const RecentThread({
    required this.roomId,
    required this.rootEventId,
    required this.root,
    this.latestReply,
    required this.replyCount,
    required this.activityMs,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      rootEventId.hashCode ^
      root.hashCode ^
      latestReply.hashCode ^
      replyCount.hashCode ^
      activityMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentThread &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          rootEventId == other.rootEventId &&
          root == other.root &&
          latestReply == other.latestReply &&
          replyCount == other.replyCount &&
          activityMs == other.activityMs;
}

class RecentThreadsSnapshot {
  final RecentThreadsStatus status;
  final List<RecentThread> threads;

  const RecentThreadsSnapshot({
    required this.status,
    required this.threads,
  });

  @override
  int get hashCode => status.hashCode ^ threads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentThreadsSnapshot &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          threads == other.threads;
}

enum RecentThreadsStatus {
  loading,
  ready,
  failed,
}
