// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_sdk`, `new`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RoomTimeline>>
abstract class RoomTimeline implements RustOpaqueInterface {
  Future<void> cancel({required String itemId});

  Future<void> markAsRead();

  Future<RoomTimeline> openThread({required String rootEventId});

  Future<bool> paginateBackwards();

  Future<void> retry({required String itemId});

  Future<void> sendMarkdown({required String body});

  Future<void> sendReply({required String body, required String inReplyTo});

  Stream<TimelineSnapshot> watch();
}

enum MessageKind {
  text,
  notice,
  emote,
  image,
  file,
  encrypted,
  redacted,
  other,
}

class ReplyPreview {
  final String eventId;
  final ReplyState state;
  final bool isOwn;
  final String? senderName;
  final MessageKind? kind;
  final String? body;

  const ReplyPreview({
    required this.eventId,
    required this.state,
    required this.isOwn,
    this.senderName,
    this.kind,
    this.body,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      state.hashCode ^
      isOwn.hashCode ^
      senderName.hashCode ^
      kind.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplyPreview &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          state == other.state &&
          isOwn == other.isOwn &&
          senderName == other.senderName &&
          kind == other.kind &&
          body == other.body;
}

enum ReplyState {
  loading,
  ready,
  unavailable,
}

enum SendState {
  sent,
  sending,
  failed,
  rejected,
}

class ThreadInfo {
  final String rootEventId;
  final int replies;
  final String? latestSender;
  final PlatformInt64? latestTimestampMs;
  final int unread;

  const ThreadInfo({
    required this.rootEventId,
    required this.replies,
    this.latestSender,
    this.latestTimestampMs,
    required this.unread,
  });

  @override
  int get hashCode =>
      rootEventId.hashCode ^
      replies.hashCode ^
      latestSender.hashCode ^
      latestTimestampMs.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadInfo &&
          runtimeType == other.runtimeType &&
          rootEventId == other.rootEventId &&
          replies == other.replies &&
          latestSender == other.latestSender &&
          latestTimestampMs == other.latestTimestampMs &&
          unread == other.unread;
}

class TimelineEntry {
  final PlatformInt64? dateDividerMs;
  final TimelineMessage? message;

  const TimelineEntry({
    this.dateDividerMs,
    this.message,
  });

  @override
  int get hashCode => dateDividerMs.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineEntry &&
          runtimeType == other.runtimeType &&
          dateDividerMs == other.dateDividerMs &&
          message == other.message;
}

class TimelineError implements FrbException {
  final TimelineErrorKind kind;
  final String message;

  const TimelineError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum TimelineErrorKind {
  roomNotFound,
  messageNotFound,
  network,
  unknown,
}

class TimelineMessage {
  final String id;
  final String? eventId;
  final String senderId;
  final String senderName;
  final bool isOwn;
  final PlatformInt64 timestampMs;
  final MessageKind kind;
  final String? body;
  final bool edited;
  final SendState sendState;
  final bool canReply;
  final ThreadInfo? thread;
  final ReplyPreview? replyTo;
  final List<String> readBy;

  const TimelineMessage({
    required this.id,
    this.eventId,
    required this.senderId,
    required this.senderName,
    required this.isOwn,
    required this.timestampMs,
    required this.kind,
    this.body,
    required this.edited,
    required this.sendState,
    required this.canReply,
    this.thread,
    this.replyTo,
    required this.readBy,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      eventId.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      isOwn.hashCode ^
      timestampMs.hashCode ^
      kind.hashCode ^
      body.hashCode ^
      edited.hashCode ^
      sendState.hashCode ^
      canReply.hashCode ^
      thread.hashCode ^
      replyTo.hashCode ^
      readBy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          eventId == other.eventId &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          isOwn == other.isOwn &&
          timestampMs == other.timestampMs &&
          kind == other.kind &&
          body == other.body &&
          edited == other.edited &&
          sendState == other.sendState &&
          canReply == other.canReply &&
          thread == other.thread &&
          replyTo == other.replyTo &&
          readBy == other.readBy;
}

class TimelineSnapshot {
  final List<TimelineEntry> items;
  final bool reachedStart;
  final bool paginating;

  const TimelineSnapshot({
    required this.items,
    required this.reachedStart,
    required this.paginating,
  });

  @override
  int get hashCode =>
      items.hashCode ^ reachedStart.hashCode ^ paginating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineSnapshot &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          reachedStart == other.reachedStart &&
          paginating == other.paginating;
}
